import { describe, it, expect, vi, afterEach, beforeAll } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/preact';
import { createElement } from 'preact';
import { DialogComponent } from '../dialog';
import { WidgetOptions } from '@/interfaces/widget-options';
import { Presentation } from '@/interfaces/presentation';

vi.mock('../player', () => ({
  PlayerComponent: ({ presentation }: { presentation: Presentation }) => createElement('div', {
    'data-player-url': presentation.player,
    'data-testid': 'player-component',
  }, `Player for ${presentation.title}`),
}));

vi.mock('../../../assets/close.svg?raw', () => ({
  default: '<svg><path d="M6 18L18 6M6 6l12 12"/></svg>',
}));

vi.mock('@/components/thumbnail', () => ({
  ThumbnailComponent: ({ onClick, presentation }: {
    presentation: { title: string };
    onClick(): void;
  }) => createElement('button', {
    'data-testid': 'thumbnail-component',
    onClick,
  }, `Thumbnail: ${presentation.title}`),
}));

describe('DialogComponent', () => {
  const mockPresentation: Presentation = {
    guid: 'test-guid',
    mediaDisplayHeight: 1280,
    mediaDisplayWidth: 1920,
    player: 'https://example.com/player',
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://cdn.example.com/thumbnail.jpg',
      height: 200,
      url: 'https://example.com/thumbnail.jpg',
      width: 300,
    },
    title: 'Test Presentation',
  };

  const mockOptions: WidgetOptions = {
    playbackMode: 'modal' as const,
    playerConfigurationGuid: 'test-config',
    playIcon: {
      height: 64,
      position: 'center',
      url: 'https://example.com/play-icon.svg',
      width: 64,
    },
  };

  const mockOnIframeReady = vi.fn();

  beforeAll(() => {
    Object.defineProperty(HTMLElement.prototype, 'showModal', {
      value: vi.fn(),
      writable: true,
    });

    Object.defineProperty(HTMLElement.prototype, 'close', {
      value: vi.fn(),
      writable: true,
    });
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('should render empty string when presentation is null', () => {
    const { container } = render(createElement(DialogComponent, {
      onIframeReady: mockOnIframeReady,
      playerParameters: {},
      presentation: null as unknown as Presentation,
      widgetOptions: mockOptions,
    }));

    expect(container.textContent).toBe('');
  });

  it('should render thumbnail component when presentation is provided', async () => {
    render(createElement(DialogComponent, {
      onIframeReady: mockOnIframeReady,
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    expect(thumbnail).toBeInTheDocument();
    expect(thumbnail).toHaveTextContent('Thumbnail: Test Presentation');
  });

  it('should show dialog when thumbnail is clicked', async () => {
    render(createElement(DialogComponent, {
      onIframeReady: mockOnIframeReady,
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const dialog = document.querySelector('dialog');

      expect(dialog).toBeInTheDocument();
    });
  });

  it('should render PlayerComponent in dialog', async () => {
    render(createElement(DialogComponent, {
      onIframeReady: mockOnIframeReady,
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const playerComponent = screen.getByTestId('player-component');

      expect(playerComponent).toBeInTheDocument();
      expect(playerComponent).toHaveTextContent('Player for Test Presentation');
    });
  });

  it('should close dialog when close button is clicked', async () => {
    const closeSpy = vi.fn();

    render(createElement(DialogComponent, {
      onIframeReady: mockOnIframeReady,
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const dialog = document.querySelector('dialog');

      expect(dialog).toBeInTheDocument();
    });

    const dialog = document.querySelector('dialog') as HTMLDialogElement;

    dialog.close = closeSpy;

    const closeButton = document.querySelector('.qc-dialog__close-button');

    expect(closeButton).toBeInTheDocument();

    fireEvent.click(closeButton!);

    expect(closeSpy).toHaveBeenCalled();
  });

  it('should close dialog when clicking on dialog backdrop', async () => {
    const closeSpy = vi.fn();

    render(createElement(DialogComponent, {
      onIframeReady: mockOnIframeReady,
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const dialog = document.querySelector('dialog');

      expect(dialog).toBeInTheDocument();
    });

    const dialog = document.querySelector('dialog') as HTMLDialogElement;

    dialog.close = closeSpy;

    fireEvent.click(dialog);

    expect(closeSpy).toHaveBeenCalled();
  });

  it('should not close dialog when clicking on dialog content', async () => {
    const closeSpy = vi.fn();

    render(createElement(DialogComponent, {
      onIframeReady: mockOnIframeReady,
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const dialog = document.querySelector('dialog');

      expect(dialog).toBeInTheDocument();
    });

    const dialog = document.querySelector('dialog') as HTMLDialogElement;

    dialog.close = closeSpy;

    const dialogContent = document.querySelector('.qc-dialog');

    expect(dialogContent).toBeInTheDocument();

    fireEvent.click(dialogContent!);

    expect(closeSpy).not.toHaveBeenCalled();
  });

  it('should handle dialog onClose event', async () => {
    render(createElement(DialogComponent, {
      onIframeReady: mockOnIframeReady,
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const dialog = document.querySelector('dialog');

      expect(dialog).toBeInTheDocument();
    });

    const dialog = document.querySelector('dialog') as HTMLDialogElement;

    fireEvent(dialog, new Event('close'));

    await waitFor(() => {
      const dialogAfterClose = document.querySelector('dialog');

      expect(dialogAfterClose).not.toBeInTheDocument();
    });
  });

  it('should execute autoplay URL modification when playbackMode is inline-autoplay', async () => {
    const optionsWithAutoplay: WidgetOptions = {
      ...mockOptions,
      playbackMode: 'inline-autoplay',
    };

    render(createElement(DialogComponent, {
      onIframeReady: mockOnIframeReady,
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: optionsWithAutoplay,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const playerComponent = screen.getByTestId('player-component');

      expect(playerComponent).toBeInTheDocument();
    });
  });

  it('should execute autoplay URL modification when playbackMode is inline', async () => {
    const optionsWithAutoplayFalse: WidgetOptions = {
      ...mockOptions,
      playbackMode: 'inline',
    };

    render(createElement(DialogComponent, {
      onIframeReady: mockOnIframeReady,
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: optionsWithAutoplayFalse,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const playerComponent = screen.getByTestId('player-component');

      expect(playerComponent).toBeInTheDocument();
    });
  });

  it('should skip autoplay URL modification when playbackMode is inline-autoload', async () => {
    const optionsWithAutoplayNull: WidgetOptions = {
      ...mockOptions,
      playbackMode: 'inline-autoload',
    };

    render(createElement(DialogComponent, {
      onIframeReady: mockOnIframeReady,
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: optionsWithAutoplayNull,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const playerComponent = screen.getByTestId('player-component');

      expect(playerComponent).toBeInTheDocument();
    });
  });
});
