import { describe, it, expect, vi, afterEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/preact';
import { createElement } from 'preact';
import { PlayerComponent } from '../player';
import { WidgetOptions } from '@/interfaces/widget-options';
import { Presentation } from '@/interfaces/presentation';
import { PlayerParameters } from '@/interfaces/player-parameters';

describe('PlayerComponent', () => {
  const mockPresentation: Presentation = {
    guid: 'test-guid',
    player: 'https://example.com/player',
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://cdn.example.com/thumbnail.jpg',
      height: 200,
      url: 'https://example.com/thumbnail.jpg',
      width: 300,
    },
    title: 'Test Presentation',
  };

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('should render empty content when presentation is null', async () => {
    // eslint-disable-next-line @typescript-eslint/require-await
    await expect(async () => {
      const { container } = render(createElement(PlayerComponent, {
        playerParameters: {} as PlayerParameters,
        presentation: null as unknown as Presentation,
        widgetOptions: {} as WidgetOptions,
      }));

      expect(container.textContent).toMatch('');
    }).rejects.toThrow();
  });

  it('should render thumbnail when playbackMode is inline', () => {
    const widgetOptions = {
      playbackMode: 'inline',
    } as WidgetOptions;

    render(createElement(PlayerComponent, {
      playerParameters: {} as PlayerParameters,
      presentation: mockPresentation,
      widgetOptions,
    }));

    const thumbnail = screen.getByAltText('Thumbnail for Test Presentation');

    expect(thumbnail).toBeInTheDocument();
    expect(thumbnail).toHaveAttribute('src', 'https://cdn.example.com/thumbnail.jpg');
  });

  it('should render thumbnail url if no cdnUrl is present', () => {
    const widgetOptions = {
      playbackMode: 'inline',
    } as WidgetOptions;

    const presentation: Presentation = {
      ...mockPresentation,
      thumbnail: {
        ...mockPresentation.thumbnail!,
      },
    };

    delete presentation.thumbnail!.cdnUrl;

    render(createElement(PlayerComponent, {
      playerParameters: {} as PlayerParameters,
      presentation,
      widgetOptions,
    }));

    const thumbnail = screen.getByAltText('Thumbnail for Test Presentation');

    expect(thumbnail).toBeInTheDocument();
    expect(thumbnail).toHaveAttribute('src', 'https://example.com/thumbnail.jpg');
  });

  it('should render iframe when playbackMode is inline-autoload', () => {
    const widgetOptions = {
      playbackMode: 'inline-autoload',
    } as WidgetOptions;

    render(createElement(PlayerComponent, {
      playerParameters: {} as PlayerParameters,
      presentation: mockPresentation,
      widgetOptions,
    }));

    const iframe = screen.getByTitle('Qumu Player');

    expect(iframe).toBeInTheDocument();
    expect(iframe).toHaveAttribute('src', 'https://example.com/player?autoplay=false');
    expect(iframe).toHaveAttribute('width', '100%');
    expect(iframe).toHaveAttribute('height', '100%');
    expect(iframe).toHaveAttribute('allow', 'autoplay; fullscreen');
  });

  it('should switch from thumbnail to iframe when thumbnail is clicked', () => {
    render(createElement(PlayerComponent, {
      playerParameters: {} as PlayerParameters,
      presentation: mockPresentation,
      widgetOptions: {
        playbackMode: 'inline',
      } as WidgetOptions,
    }));

    expect(screen.getByAltText('Thumbnail for Test Presentation')).toBeInTheDocument();
    expect(screen.queryByTitle('Qumu Player')).not.toBeInTheDocument();

    const thumbnailButton = screen.getByRole('button');

    fireEvent.click(thumbnailButton);

    expect(screen.getByTitle('Qumu Player')).toBeInTheDocument();
    expect(screen.queryByAltText('Thumbnail for Test Presentation')).not.toBeInTheDocument();
  });

  it('should call onIframeReady when iframe loads', () => {
    const onIframeReady = vi.fn();
    const widgetOptions: WidgetOptions = {
      playbackMode: 'inline-autoload',
    } as WidgetOptions;

    render(createElement(PlayerComponent, {
      onIframeReady,
      playerParameters: {} as PlayerParameters,
      presentation: mockPresentation,
      widgetOptions,
    }));

    const iframe = screen.getByTitle('Qumu Player');

    fireEvent.load(iframe);

    expect(onIframeReady).toHaveBeenCalledWith(iframe);
  });

  it('should throw an error when no player parameter is provided in the presentation', async () => {
    const widgetOptions = {
      playbackMode: 'inline-autoload',
    } as WidgetOptions;

    const presentation: Presentation = {
      ...mockPresentation,
      player: undefined,
    };

    await expect(async () => {
      render(createElement(PlayerComponent, {
        playerParameters: {} as PlayerParameters,
        presentation,
        widgetOptions,
      }));

      await new Promise((resolve) => setTimeout(resolve, 0));
    }).rejects.toThrow();
  });

  describe('playerParameters', () => {
    it('should set player parameters in iframe src', () => {
      const widgetOptions = {
        playbackMode: 'inline-autoload',
      } as WidgetOptions;

      const playerParameters: Partial<PlayerParameters> = {
        captions: 'en',
        debug: true,
        loop: true,
        pv: 'sbs',
        quality: '720p',
        reporting: true,
        reportingId: 'my-reporting-id-12345',
        showControlPanel: true,
        sidebar: true,
        speech: '',
        speechTerm: '',
        start: 45,
        volume: 50,
      };

      render(createElement(PlayerComponent, {
        playerParameters,
        presentation: mockPresentation,
        widgetOptions,
      }));

      const iframe = screen.getByTitle('Qumu Player');

      expect(iframe).toHaveAttribute(
        'src',
        'https://example.com/player?autoplay=false&captions=en&debug=true&loop=true&pv=sbs&quality=720p&reporting=true&reportingId=my-reporting-id-12345&showControlPanel=true&sidebar=true&speech=&speechTerm=&start=45&volume=50',
      );
    });
  });

  describe('widgetOptions', () => {
    it('should set playerConfigurationGuid parameter when provided', () => {
      const widgetOptions = {
        playbackMode: 'inline-autoload',
        playerConfigurationGuid: 'config-guid-123',
      } as WidgetOptions;

      render(createElement(PlayerComponent, {
        playerParameters: {} as PlayerParameters,
        presentation: mockPresentation,
        widgetOptions,
      }));

      const iframe = screen.getByTitle('Qumu Player');

      expect(iframe).toHaveAttribute('src', 'https://example.com/player?autoplay=false&playerConfigurationGuid=config-guid-123');
    });
  });
});
