import { describe, it, expect, vi, afterEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/preact';
import { createElement } from 'preact';
import { PlayerComponent } from '../player';
import { WidgetOptions } from '@/interfaces/widget-options';
import { Presentation } from '@/interfaces/presentation';

describe('PlayerComponent', () => {
  const mockPresentation: Presentation = {
    guid: 'test-guid',
    player: 'https://example.com/player',
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://cdn.example.com/thumbnail.jpg',
      height: 200,
      url: 'https://example.com/thumbnail.jpg',
      width: 300,
    },
    title: 'Test Presentation',
  };

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('should render empty content when presentation is null', async () => {
    // eslint-disable-next-line @typescript-eslint/require-await
    await expect(async () => {
      const { container } = render(createElement(PlayerComponent, {
        options: {} as WidgetOptions,
        presentation: null as unknown as Presentation,
      }));

      expect(container.textContent).toMatch('');
    }).rejects.toThrow();
  });

  it('should render thumbnail when playbackMode isinline', () => {
    const options = {
      playbackMode: 'inline',
    } as WidgetOptions;

    render(createElement(PlayerComponent, {
      options,
      presentation: mockPresentation,
    }));

    const thumbnail = screen.getByAltText('Thumbnail for Test Presentation');

    expect(thumbnail).toBeInTheDocument();
    expect(thumbnail).toHaveAttribute('src', 'https://cdn.example.com/thumbnail.jpg');
  });

  it('should render thumbnail url if no cdnUrl is present', () => {
    const options = {
      playbackMode: 'inline',
    } as WidgetOptions;

    const presentation: Presentation = {
      ...mockPresentation,
      thumbnail: {
        ...mockPresentation.thumbnail!,
      },
    };

    delete presentation.thumbnail!.cdnUrl;

    render(createElement(PlayerComponent, {
      options,
      presentation,
    }));

    const thumbnail = screen.getByAltText('Thumbnail for Test Presentation');

    expect(thumbnail).toBeInTheDocument();
    expect(thumbnail).toHaveAttribute('src', 'https://example.com/thumbnail.jpg');
  });

  it('should render iframe when playbackMode is inline-autoload', () => {
    const options = {
      playbackMode: 'inline-autoload',
    } as WidgetOptions;

    render(createElement(PlayerComponent, {
      options,
      presentation: mockPresentation,
    }));

    const iframe = screen.getByTitle('Qumu Player');

    expect(iframe).toBeInTheDocument();
    expect(iframe).toHaveAttribute('src', 'https://example.com/player?autoplay=false');
    expect(iframe).toHaveAttribute('width', '100%');
    expect(iframe).toHaveAttribute('height', '100%');
    expect(iframe).toHaveAttribute('allow', 'autoplay; fullscreen');
  });

  it('should switch from thumbnail to iframe when thumbnail is clicked', () => {
    render(createElement(PlayerComponent, {
      options: {
        playbackMode: 'inline',
      } as WidgetOptions,
      presentation: mockPresentation,
    }));

    expect(screen.getByAltText('Thumbnail for Test Presentation')).toBeInTheDocument();
    expect(screen.queryByTitle('Qumu Player')).not.toBeInTheDocument();

    const thumbnailButton = screen.getByRole('button');

    fireEvent.click(thumbnailButton);

    expect(screen.getByTitle('Qumu Player')).toBeInTheDocument();
    expect(screen.queryByAltText('Thumbnail for Test Presentation')).not.toBeInTheDocument();
  });

  it('should call onIframeReady when iframe loads', () => {
    const onIframeReady = vi.fn();
    const options: WidgetOptions = {
      playbackMode: 'inline-autoload',
    } as WidgetOptions;

    render(createElement(PlayerComponent, {
      onIframeReady,
      options,
      presentation: mockPresentation,
    }));

    const iframe = screen.getByTitle('Qumu Player');

    fireEvent.load(iframe);

    expect(onIframeReady).toHaveBeenCalledWith(iframe);
  });

  it('should throw an error when no player parameter is provided in the presentation', async () => {
    const options = {
      playbackMode: 'inline-autoload',
    } as WidgetOptions;

    const presentation: Presentation = {
      ...mockPresentation,
      player: undefined,
    };

    await expect(async () => {
      render(createElement(PlayerComponent, {
        options,
        presentation,
      }));

      await new Promise((resolve) => setTimeout(resolve, 0));
    }).rejects.toThrow();
  });

  describe('widgetOptions', () => {
    it('should set playerConfigurationGuid parameter when provided', () => {
      const options = {
        playbackMode: 'inline-autoload',
        playerConfigurationGuid: 'config-guid-123',
      } as WidgetOptions;

      render(createElement(PlayerComponent, {
        options,
        presentation: mockPresentation,
      }));

      const iframe = screen.getByTitle('Qumu Player');

      expect(iframe).toHaveAttribute('src', 'https://example.com/player?autoplay=false&playerConfigurationGuid=config-guid-123');
    });
  });
});
