import { describe, it, expect, vi, afterEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/preact';
import { createElement } from 'preact';
import { PlayerComponent } from '../player';
import { WidgetOptions } from '@/interfaces/widget-options';
import { Presentation } from '@/interfaces/presentation';

describe('PlayerComponent', () => {
  const mockPresentation: Presentation = {
    guid: 'test-guid',
    player: 'https://example.com/player',
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://cdn.example.com/thumbnail.jpg',
      height: 200,
      url: 'https://example.com/thumbnail.jpg',
      width: 300,
    },
    title: 'Test Presentation',
  };

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('should render empty content when presentation is null', () => {
    const { container } = render(createElement(PlayerComponent, { presentation: null as unknown as Presentation }));

    expect(container.textContent).toMatch('');
  });

  it('should render thumbnail when autoload is false', () => {
    const options: Partial<WidgetOptions> = {
      autoload: false,
    };

    render(createElement(PlayerComponent, {
      options,
      presentation: mockPresentation,
    }));

    const thumbnail = screen.getByAltText('Thumbnail for Test Presentation');

    expect(thumbnail).toBeInTheDocument();
    expect(thumbnail).toHaveAttribute('src', 'https://cdn.example.com/thumbnail.jpg');
  });

  it('should render thumbnail url if no cdnUrl is present', () => {
    const options: Partial<WidgetOptions> = {
      autoload: false,
    };

    const presentation: Presentation = {
      ...mockPresentation,
      thumbnail: {
        ...mockPresentation.thumbnail!,
      },
    };

    delete presentation.thumbnail!.cdnUrl;

    render(createElement(PlayerComponent, {
      options,
      presentation,
    }));

    const thumbnail = screen.getByAltText('Thumbnail for Test Presentation');

    expect(thumbnail).toBeInTheDocument();
    expect(thumbnail).toHaveAttribute('src', 'https://example.com/thumbnail.jpg');
  });

  it('should render iframe when autoload is true', () => {
    const options: Partial<WidgetOptions> = {
      autoload: true,
    };

    render(createElement(PlayerComponent, {
      options,
      presentation: mockPresentation,
    }));

    const iframe = screen.getByTitle('Qumu Player');

    expect(iframe).toBeInTheDocument();
    expect(iframe).toHaveAttribute('src', 'https://example.com/player');
    expect(iframe).toHaveAttribute('width', '100%');
    expect(iframe).toHaveAttribute('height', '100%');
    expect(iframe).toHaveAttribute('allow', 'autoplay; fullscreen');
  });

  it('should switch from thumbnail to iframe when thumbnail is clicked', async () => {
    render(createElement(PlayerComponent, {
      options: {
        autoload: false,
      },
      presentation: mockPresentation,
    }));

    expect(screen.getByAltText('Thumbnail for Test Presentation')).toBeInTheDocument();
    expect(screen.queryByTitle('Qumu Player')).not.toBeInTheDocument();

    const thumbnailButton = screen.getByRole('button');

    fireEvent.click(thumbnailButton);

    await waitFor(() => {
      expect(screen.getByTitle('Qumu Player')).toBeInTheDocument();
    });

    expect(screen.queryByAltText('Thumbnail for Test Presentation')).not.toBeInTheDocument();
  });

  it('should set autoplay parameter when autoplay option is provided', () => {
    const options: Partial<WidgetOptions> = {
      autoload: true,
      autoplay: true,
    };

    render(createElement(PlayerComponent, {
      options,
      presentation: mockPresentation,
    }));

    const iframe = screen.getByTitle('Qumu Player');

    expect(screen.getByTitle('Qumu Player')).toBeInTheDocument();
    expect(iframe).toHaveAttribute('src', 'https://example.com/player?autoplay=true');
  });

  it('should call onIframeReady when iframe loads', async () => {
    const onIframeReady = vi.fn();
    const options: Partial<WidgetOptions> = {
      autoload: true,
    };

    render(createElement(PlayerComponent, {
      onIframeReady,
      options,
      presentation: mockPresentation,
    }));

    const iframe = screen.getByTitle('Qumu Player');

    fireEvent.load(iframe);

    await waitFor(() => {
      expect(onIframeReady).toHaveBeenCalledWith(iframe);
    });
  });

  it('should use autoload false as default when options are not provided', () => {
    render(createElement(PlayerComponent, { presentation: mockPresentation }));

    expect(screen.getByAltText('Thumbnail for Test Presentation')).toBeInTheDocument();
    expect(screen.queryByTitle('Qumu Player')).not.toBeInTheDocument();
  });
});
