import { describe, it, expect, vi, afterEach, beforeEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/preact';
import { createElement } from 'preact';
import { ThumbnailComponent } from '../thumbnail';
import { WidgetOptions } from '@/interfaces/widget-options';
import { Presentation } from '@/interfaces/presentation';
import { ConfigurationService } from '@/services/configuration.service';
import type { PlayIcon, PlayIconPosition } from '@/interfaces/play-icon';

describe('ThumbnailComponent', () => {
  const mockPresentation: Presentation = {
    guid: 'test-guid',
    player: 'https://example.com/player',
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://cdn.example.com/thumbnail.jpg',
      height: 200,
      url: 'https://example.com/thumbnail.jpg',
      width: 300,
    },
    title: 'Test Presentation',
  };

  const configurationService = new ConfigurationService();
  const mockConfiguration = configurationService.setDefaults({
    guid: 'test-guid',
    host: 'https://example.com',
    selector: '#widget-container',
  });

  const mockOnClick = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
    document.head.innerHTML = '';
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  describe('Rendering', () => {
    it('should render thumbnail button with image', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: mockConfiguration.widgetOptions as WidgetOptions,
      }));

      const button = screen.getByRole('button');
      const image = screen.getByAltText('Thumbnail for Test Presentation');

      expect(button).toBeInTheDocument();
      expect(button).toHaveClass('qc-thumbnail');
      expect(image).toBeInTheDocument();
      expect(image).toHaveClass('qc-thumbnail__image');
      expect(image).toHaveAttribute('src', 'https://cdn.example.com/thumbnail.jpg');
    });

    it('should use thumbnail url when cdnUrl is not available', () => {
      const presentationWithoutCdn = {
        ...mockPresentation,
        thumbnail: {
          ...mockPresentation.thumbnail!,
          cdnUrl: undefined,
        },
      };

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: presentationWithoutCdn,
        widgetOptions: mockConfiguration.widgetOptions as WidgetOptions,
      }));

      const image = screen.getByAltText('Thumbnail for Test Presentation');

      expect(image).toHaveAttribute('src', 'https://example.com/thumbnail.jpg');
    });
  });

  describe('Play Icon', () => {
    it('should render default play icon when no custom play icon is provided', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: {
          ...mockConfiguration.widgetOptions as WidgetOptions,
          playIcon: {
            ...mockConfiguration.widgetOptions!.playIcon,
            url: undefined as unknown as string,
          } as PlayIcon,
        },
      }));

      const playIcon = screen.getByRole('button').querySelector('.qc-thumbnail__play-button--default');

      expect(playIcon).toBeInTheDocument();
      expect(playIcon).toHaveClass('qc-thumbnail__play-button');
      expect(playIcon).toHaveClass('qc-thumbnail__play-button--default');
    });

    it('should render custom play icon image when provided in options', () => {
      const widgetOptions = {
        ...mockConfiguration.widgetOptions as WidgetOptions,
        playIcon: {
          height: 50,
          url: 'https://example.com/custom-play-icon.png',
          width: 50,
        },
      } as WidgetOptions;

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions,
      }));

      const playIconImage = screen.getByAltText('Play');

      expect(playIconImage).toBeInTheDocument();
      expect(playIconImage).toHaveClass('qc-thumbnail__play-button');
      expect(playIconImage).toHaveAttribute('src', 'https://example.com/custom-play-icon.png');
      expect(playIconImage).toHaveStyle({
        height: '50px',
        width: '50px',
      });
    });

    it('should apply width and height provided in play icon options', () => {
      const widgetOptions = {
        ...mockConfiguration.widgetOptions as WidgetOptions,
        playIcon: {
          height: 40,
          url: '',
          width: 60,
        },
      } as WidgetOptions;

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions,
      }));

      const playIcon = screen.getByRole('button').querySelector('.qc-thumbnail__play-button');

      expect(playIcon!.getAttribute('width')).toBe('60');
      expect(playIcon!.getAttribute('height')).toBe('40');
    });

    it('should position play icon based on options', () => {
      const positionMap = {
        'bottom-center': ['end', 'center'],
        'bottom-left': ['end', 'start'],
        'bottom-right': ['end', 'end'],
        center: ['center', 'center'],
        left: ['center', 'start'],
        right: ['center', 'end'],
        'top-center': ['start', 'center'],
        'top-left': ['start', 'start'],
        'top-right': ['start', 'end'],
      };

      const widgetOptions = {
        ...mockConfiguration.widgetOptions as WidgetOptions,
        playIcon: {
          height: 50,
          url: 'https://example.com/custom-play-icon.png',
          width: 50,
        },
      } as WidgetOptions;

      Object.entries(positionMap).forEach(([position, [placeY, placeX]]) => {
        document.body.innerHTML = '';
        widgetOptions.playIcon.position = position as PlayIconPosition;

        render(createElement(ThumbnailComponent, {
          onClick: mockOnClick,
          presentation: mockPresentation,
          widgetOptions,
        }));

        const button = screen.getByRole('button');

        expect(button).toHaveStyle({
          'place-items': `${placeY} ${placeX}`,
        });
      });
    });
  });

  describe('Click Interaction', () => {
    it('should call onClick handler when thumbnail is clicked', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: mockConfiguration.widgetOptions as WidgetOptions,
      }));

      const button = screen.getByRole('button');

      fireEvent.click(button);

      expect(mockOnClick).toHaveBeenCalledTimes(1);
    });

    it('should call onClick handler multiple times when clicked multiple times', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: mockConfiguration.widgetOptions as WidgetOptions,
      }));

      const button = screen.getByRole('button');

      fireEvent.click(button);
      fireEvent.click(button);
      fireEvent.click(button);

      expect(mockOnClick).toHaveBeenCalledTimes(3);
    });

    it('should call onThumbnailClick from widgetOptions if provided', () => {
      const mockOnThumbnailClick = vi.fn();
      const widgetOptions: Partial<WidgetOptions> = {
        ...mockConfiguration.widgetOptions as WidgetOptions,
        onThumbnailClick: mockOnThumbnailClick,
      };

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions,
      }));

      const button = screen.getByRole('button');

      fireEvent.click(button);

      expect(mockOnThumbnailClick).toHaveBeenCalledTimes(1);
      expect(mockOnThumbnailClick).toHaveBeenCalledWith(mockPresentation);
      expect(mockOnClick).not.toHaveBeenCalled();
    });
  });

  describe('Accessibility', () => {
    it('should have proper button type attribute', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: {
          ...mockConfiguration.widgetOptions as WidgetOptions,
          playIcon: {
            height: 100,
            position: 'bottom-left',
            width: 100,
          },
        } as WidgetOptions,
      }));

      const button = screen.getByRole('button');

      expect(button).toHaveAttribute('type', 'button');
    });

    it('should have descriptive alt text for thumbnail image', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: {
          ...mockConfiguration.widgetOptions as WidgetOptions,
          playIcon: {
            height: 100,
            position: 'bottom-left',
            width: 100,
          },
        } as WidgetOptions,
      }));

      const image = screen.getByAltText('Thumbnail for Test Presentation');

      expect(image).toHaveAttribute('alt', 'Thumbnail for Test Presentation');
    });

    it('should have alt text for custom play icon', () => {
      const widgetOptions = {
        ...mockConfiguration.widgetOptions as WidgetOptions,
        playIcon: {
          height: 50,
          url: 'https://example.com/custom-play-icon.png',
          width: 50,
        },
      } as WidgetOptions;

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions,
      }));

      const playIcon = screen.getByAltText('Play');

      expect(playIcon).toHaveAttribute('alt', 'Play');
    });
  });
});
