import { describe, it, expect, vi, afterEach, beforeEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/preact';
import { createElement } from 'preact';
import { ThumbnailComponent } from '../thumbnail';
import { WidgetOptions } from '@/interfaces/widget-options';
import { Presentation } from '@/interfaces/presentation';

vi.mock('../../../assets/play-icon.svg?raw', () => ({
  default: '<svg><circle cx="50" cy="50" r="40"/></svg>',
}));

describe('ThumbnailComponent', () => {
  const mockPresentation: Presentation = {
    guid: 'test-guid',
    player: 'https://example.com/player',
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://cdn.example.com/thumbnail.jpg',
      height: 200,
      url: 'https://example.com/thumbnail.jpg',
      width: 300,
    },
    title: 'Test Presentation',
  };

  const mockOnClick = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
    document.head.innerHTML = '';
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  describe('Rendering', () => {
    it('should render thumbnail button with image', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options: {} as WidgetOptions,
        presentation: mockPresentation,
      }));

      const button = screen.getByRole('button');
      const image = screen.getByAltText('Thumbnail for Test Presentation');

      expect(button).toBeInTheDocument();
      expect(button).toHaveClass('qc-thumbnail');
      expect(image).toBeInTheDocument();
      expect(image).toHaveClass('qc-thumbnail__image');
      expect(image).toHaveAttribute('src', 'https://cdn.example.com/thumbnail.jpg');
    });

    it('should use thumbnail url when cdnUrl is not available', () => {
      const presentationWithoutCdn = {
        ...mockPresentation,
        thumbnail: {
          ...mockPresentation.thumbnail!,
          cdnUrl: undefined,
        },
      };

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options: {} as WidgetOptions,
        presentation: presentationWithoutCdn,
      }));

      const image = screen.getByAltText('Thumbnail for Test Presentation');

      expect(image).toHaveAttribute('src', 'https://example.com/thumbnail.jpg');
    });
  });

  describe('Play Icon', () => {
    it('should render default play icon when no custom play icon is provided', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options: {} as WidgetOptions,
        presentation: mockPresentation,
      }));

      const playIcon = screen.getByRole('button').querySelector('.qc-thumbnail__play-button--default');

      expect(playIcon).toBeInTheDocument();
      expect(playIcon).toHaveClass('qc-thumbnail__play-button');
      expect(playIcon).toHaveClass('qc-thumbnail__play-button--default');
    });

    it('should render custom play icon image when provided in options', () => {
      const options = {
        playIcon: {
          height: 50,
          url: 'https://example.com/custom-play-icon.png',
          width: 50,
        },
      } as WidgetOptions;

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options,
        presentation: mockPresentation,
      }));

      const playIconImage = screen.getByAltText('Play');

      expect(playIconImage).toBeInTheDocument();
      expect(playIconImage).toHaveClass('qc-thumbnail__play-button');
      expect(playIconImage).toHaveAttribute('src', 'https://example.com/custom-play-icon.png');
      expect(playIconImage).toHaveStyle({
        height: '50px',
        width: '50px',
      });
    });

    it('should apply width style when provided in play icon options', () => {
      const options = {
        playIcon: {
          height: 40,
          url: '',
          width: 60,
        },
      } as WidgetOptions;

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options,
        presentation: mockPresentation,
      }));

      const playIcon = screen.getByRole('button').querySelector('.qc-thumbnail__play-button');

      expect(playIcon).toHaveStyle({
        height: '40px',
        width: '60px',
      });
    });

    it('should apply height style when provided in play icon options', () => {
      const options = {
        playIcon: {
          height: 75,
          url: '',
          width: 50,
        },
      } as WidgetOptions;

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options,
        presentation: mockPresentation,
      }));

      const playIcon = screen.getByRole('button').querySelector('.qc-thumbnail__play-button--default');

      expect(playIcon).toHaveStyle({
        height: '75px',
        width: '50px',
      });
    });

    it('should not apply size styles when not provided in options', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options: {
          playIcon: {
            url: 'https://example.com/custom-play-icon.png',
          },
        } as WidgetOptions,
        presentation: mockPresentation,
      }));

      const playIcon = screen.getByRole('button').querySelector('.qc-thumbnail__play-button');

      expect(playIcon?.getAttribute('style')).toBeNull();
    });
  });

  describe('Click Interaction', () => {
    it('should call onClick handler when thumbnail is clicked', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options: {} as WidgetOptions,
        presentation: mockPresentation,
      }));

      const button = screen.getByRole('button');

      fireEvent.click(button);

      expect(mockOnClick).toHaveBeenCalledTimes(1);
    });

    it('should call onClick handler multiple times when clicked multiple times', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options: {} as WidgetOptions,
        presentation: mockPresentation,
      }));

      const button = screen.getByRole('button');

      fireEvent.click(button);
      fireEvent.click(button);
      fireEvent.click(button);

      expect(mockOnClick).toHaveBeenCalledTimes(3);
    });
  });

  describe('Edge Cases', () => {
    it('should handle partial play icon options', () => {
      const options = {
        playIcon: {
          width: 40,
        },
      } as WidgetOptions;

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options,
        presentation: mockPresentation,
      }));

      const playIcon = screen.getByRole('button').querySelector('.qc-thumbnail__play-button--default');
      const playIconStyle = playIcon?.getAttribute('style');

      expect(playIconStyle).not.toContain('height');
      expect(playIconStyle).toContain('width: 40px;');
    });

    it('should handle empty play icon url', () => {
      const options = {
        playIcon: {
          height: 50,
          url: '',
          width: 50,
        },
      } as WidgetOptions;

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options,
        presentation: mockPresentation,
      }));

      const playIcon = screen.getByRole('button').querySelector('.qc-thumbnail__play-button--default');

      expect(playIcon).toBeInTheDocument();
      expect(screen.queryByAltText('Play')).not.toBeInTheDocument();
    });
  });

  describe('Accessibility', () => {
    it('should have proper button type attribute', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options: {} as WidgetOptions,
        presentation: mockPresentation,
      }));

      const button = screen.getByRole('button');

      expect(button).toHaveAttribute('type', 'button');
    });

    it('should have descriptive alt text for thumbnail image', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options: {} as WidgetOptions,
        presentation: mockPresentation,
      }));

      const image = screen.getByAltText('Thumbnail for Test Presentation');

      expect(image).toHaveAttribute('alt', 'Thumbnail for Test Presentation');
    });

    it('should have alt text for custom play icon', () => {
      const options = {
        playIcon: {
          height: 50,
          url: 'https://example.com/custom-play-icon.png',
          width: 50,
        },
      } as WidgetOptions;

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        options,
        presentation: mockPresentation,
      }));

      const playIcon = screen.getByAltText('Play');

      expect(playIcon).toHaveAttribute('alt', 'Play');
    });
  });
});
