import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { PresentationWidget } from '../presentation-widget';
import { WidgetConfiguration } from '@/interfaces/widget-configuration';
import { PresentationService } from '@/services/presentation.service';
import { Presentation } from '@/interfaces/presentation';

vi.mock('@/services/presentation.service');
vi.mock('preact', () => ({
  render: vi.fn(),
}));

const mockRender = vi.mocked((await import('preact')).render);

describe('PresentationWidget', () => {
  const mockConfiguration: WidgetConfiguration = {
    guid: 'test-guid',
    host: 'example.com',
    selector: '.widget-container',
    widgetOptions: {
      autoload: false,
      info: {
        bottom: [],
        left: [],
        over: [],
        right: [],
        top: [],
      },
    },
  };

  const mockPresentation: Presentation = {
    guid: 'test-guid',
    player: 'https://example.com/player',
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://example.com/thumbnail.jpg',
      height: 200,
      url: 'https://example.com/thumbnail.jpg',
      width: 300,
    },
    title: 'Test Presentation',
  };

  let mockContainer: HTMLElement;
  let getPresentationMock: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    vi.clearAllMocks();

    mockContainer = {
      innerHTML: '',
    } as HTMLElement;

    document.querySelector = vi.fn().mockReturnValue(mockContainer);

    getPresentationMock = vi.fn().mockResolvedValue(mockPresentation);

    vi.spyOn(PresentationService.prototype, 'getPresentation').mockImplementation(getPresentationMock as () => Promise<Presentation>);
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  describe('constructor', () => {
    it('should initialize widget', () => {
      const widget = new PresentationWidget(mockConfiguration);

      expect(widget).toBeDefined();
    });

    it('should validate the configuration and throw an error', () => {
      const invalidConfig = {
        ...mockConfiguration,
        host: '   ',
      };

      expect(() => new PresentationWidget(invalidConfig)).toThrow('`host` cannot be an empty string');
    });
  });

  describe('getIframe', () => {
    it('should return a promise that resolves to HTMLIFrameElement', async () => {
      const widget = new PresentationWidget(mockConfiguration);
      const iframePromise = widget.getIframe();

      expect(iframePromise).toBeInstanceOf(Promise);

      await new Promise((resolve) => setTimeout(resolve, 0));

      expect(getPresentationMock).toHaveBeenCalledWith(
        'test-guid',
        'example.com',
      );
    });

    it('should reject promise when presentation service fails', async () => {
      const error = new Error('Service error');

      getPresentationMock.mockRejectedValue(error);

      const widget = new PresentationWidget(mockConfiguration);
      const iframePromise = widget.getIframe();

      await expect(iframePromise).rejects.toThrow('Service error');
    });
  });

  describe('init', () => {
    it('should fetch presentation and mount component', async () => {
      // eslint-disable-next-line no-new
      new PresentationWidget(mockConfiguration);

      await new Promise((resolve) => setTimeout(resolve, 0));

      expect(getPresentationMock).toHaveBeenCalledWith(
        'test-guid',
        'example.com',
      );

      expect(document.querySelector).toHaveBeenCalledWith('.widget-container');
      expect(mockContainer.innerHTML).toBe('');
      expect(mockRender).toHaveBeenCalled();
    });

    it('throws error when container element is not found', async () => {
      document.querySelector = vi.fn().mockReturnValue(null);

      const widget = new PresentationWidget(mockConfiguration);

      await expect(widget.getIframe()).rejects.toThrow('Element for selector ".widget-container" not found');
    });

    it('handles presentation service errors', async () => {
      const error = new Error('Network error');

      getPresentationMock.mockRejectedValue(error);

      const widget = new PresentationWidget(mockConfiguration);

      await expect(widget.getIframe()).rejects.toThrow('Network error');
    });
  });

  describe('mount', () => {
    it('renders widget with presentation title and player component', async () => {
      // eslint-disable-next-line no-new
      new PresentationWidget(mockConfiguration);

      await new Promise((resolve) => setTimeout(resolve, 0));

      expect(mockRender).toHaveBeenCalledTimes(1);

      const renderCall = mockRender.mock.calls[0];

      expect(renderCall[1]).toBe(mockContainer);

      const renderedElement = renderCall[0];

      expect(renderedElement).toBeDefined();
    });

    it('clears container innerHTML before mounting', async () => {
      mockContainer.innerHTML = '<div>existing content</div>';

      // eslint-disable-next-line no-new
      new PresentationWidget(mockConfiguration);

      // Wait for async init to complete
      await new Promise((resolve) => setTimeout(resolve, 0));

      expect(mockContainer.innerHTML).toBe('');
    });
  });
});
