import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { PresentationWidget } from '@/widgets/presentation-widget';
import { WidgetConfiguration } from '@/interfaces/widget-configuration';
import { PresentationService } from '@/services/presentation.service';
import { Presentation } from '@/interfaces/presentation';

vi.mock('@/services/presentation.service');

describe('PresentationWidget', () => {
  const mockConfiguration: WidgetConfiguration = {
    guid: 'test-guid',
    host: 'example.com',
    selector: '.widget-container',
    widgetOptions: {
      playbackMode: 'inline',
    },
  };

  const mockPresentation: Presentation = {
    guid: 'test-guid',
    player: 'https://example.com/player',
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://example.com/thumbnail.jpg',
      height: 200,
      url: 'https://example.com/thumbnail.jpg',
      width: 300,
    },
    title: 'Test Presentation',
  };

  let container: HTMLElement;
  let getPresentationMock: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    vi.clearAllMocks();

    container = document.createElement('div');
    container.classList.add('widget-container');
    document.body.appendChild(container);

    getPresentationMock = vi.fn().mockResolvedValue(mockPresentation);

    vi.spyOn(PresentationService.prototype, 'getPresentation')
      .mockImplementation(getPresentationMock as () => Promise<Presentation>);
  });

  afterEach(() => {
    document.body.removeChild(container);
    vi.restoreAllMocks();
  });

  describe('constructor', () => {
    it('should initialize widget', () => {
      const widget = new PresentationWidget(mockConfiguration);

      expect(widget).toBeDefined();
    });

    it('should validate the configuration and throw an error', () => {
      const invalidConfig = {
        ...mockConfiguration,
        host: '   ',
      };

      expect(() => new PresentationWidget(invalidConfig)).toThrow('`host` cannot be an empty string');
    });
  });

  describe('getIframe', () => {
    it('should return a promise that resolves to HTMLIFrameElement', async () => {
      const widget = new PresentationWidget(mockConfiguration);
      const iframePromise = widget.getIframe();

      expect(iframePromise).toBeInstanceOf(Promise);

      await Promise.resolve();

      expect(getPresentationMock).toHaveBeenCalledWith(
        'test-guid',
        'example.com',
      );
    });

    it('should reject promise when presentation service fails', async () => {
      const error = new Error('Service error');

      getPresentationMock.mockRejectedValue(error);

      const widget = new PresentationWidget(mockConfiguration);
      const iframePromise = widget.getIframe();

      await expect(iframePromise).rejects.toThrow('Service error');
    });
  });

  describe('init', () => {
    it('should fetch presentation and mount component', async () => {
      const querySelectorSpy = vi.spyOn(document, 'querySelector');

      // eslint-disable-next-line no-new
      new PresentationWidget(mockConfiguration);

      await Promise.resolve();

      expect(getPresentationMock).toHaveBeenCalledWith(
        'test-guid',
        'example.com',
      );

      expect(querySelectorSpy).toHaveBeenCalledWith('.widget-container');
      expect(container.innerHTML)
        .toMatchInlineSnapshot(`"<div class="qc-widget qc-presentation-widget"><button type="button" class="qc-thumbnail" style="place-items: center center;"><img class="qc-thumbnail__image" src="https://example.com/thumbnail.jpg" alt="Thumbnail for Test Presentation"><div class="qc-thumbnail__play-button qc-thumbnail__play-button--default"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="currentColor" width="64" height="64"><path d="M22.643 17.734a1 1 0 000-1.696L12.417 9.647a1 1 0 00-1.53.848v12.783a1 1 0 001.53.848l10.226-6.392zm-9.166 8.088a3 3 0 01-4.59-2.544V10.495a3 3 0 014.59-2.544l10.226 6.391a3 3 0 010 5.088l-10.226 6.392z"></path></svg></div></button></div>"`);
    });

    it('throws error when container element is not found', async () => {
      vi.spyOn(document, 'querySelector').mockReturnValue(null);

      const widget = new PresentationWidget(mockConfiguration);

      await Promise.resolve();

      await expect(widget.getIframe()).rejects.toThrow('Element for selector ".widget-container" not found');
    });

    it('handles presentation service errors', async () => {
      const error = new Error('Network error');

      getPresentationMock.mockRejectedValue(error);

      const widget = new PresentationWidget(mockConfiguration);

      await expect(widget.getIframe()).rejects.toThrow('Network error');
    });
  });

  describe('mount', () => {
    it('renders widget with presentation title and player component', async () => {
      // eslint-disable-next-line no-new
      new PresentationWidget(mockConfiguration);

      await Promise.resolve();

      expect(container.innerHTML).toMatchInlineSnapshot(`"<div class="qc-widget qc-presentation-widget"><button type="button" class="qc-thumbnail" style="place-items: center center;"><img class="qc-thumbnail__image" src="https://example.com/thumbnail.jpg" alt="Thumbnail for Test Presentation"><div class="qc-thumbnail__play-button qc-thumbnail__play-button--default"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="currentColor" width="64" height="64"><path d="M22.643 17.734a1 1 0 000-1.696L12.417 9.647a1 1 0 00-1.53.848v12.783a1 1 0 001.53.848l10.226-6.392zm-9.166 8.088a3 3 0 01-4.59-2.544V10.495a3 3 0 014.59-2.544l10.226 6.391a3 3 0 010 5.088l-10.226 6.392z"></path></svg></div></button></div>"`);
    });

    it('uses HTMLElement from selector if provided', async () => {
      const querySelectorSpy = vi.spyOn(document, 'querySelector');
      const element = document.createElement('div');
      const configWithHTMLElement: WidgetConfiguration = {
        ...mockConfiguration,
        selector: element,
      };

      // eslint-disable-next-line no-new
      new PresentationWidget(configWithHTMLElement);

      await Promise.resolve();

      expect(querySelectorSpy).not.toHaveBeenCalled();
      expect(element.innerHTML).toMatchInlineSnapshot(`"<div class="qc-widget qc-presentation-widget"><button type="button" class="qc-thumbnail" style="place-items: center center;"><img class="qc-thumbnail__image" src="https://example.com/thumbnail.jpg" alt="Thumbnail for Test Presentation"><div class="qc-thumbnail__play-button qc-thumbnail__play-button--default"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="currentColor" width="64" height="64"><path d="M22.643 17.734a1 1 0 000-1.696L12.417 9.647a1 1 0 00-1.53.848v12.783a1 1 0 001.53.848l10.226-6.392zm-9.166 8.088a3 3 0 01-4.59-2.544V10.495a3 3 0 014.59-2.544l10.226 6.391a3 3 0 010 5.088l-10.226 6.392z"></path></svg></div></button></div>"`);
    });

    it('clears container innerHTML before mounting', async () => {
      container.innerHTML = '<div>existing content</div>';

      // eslint-disable-next-line no-new
      new PresentationWidget(mockConfiguration);

      // Wait for async init to complete
      await Promise.resolve();

      expect(container.innerHTML).toMatchInlineSnapshot(`"<div class="qc-widget qc-presentation-widget"><button type="button" class="qc-thumbnail" style="place-items: center center;"><img class="qc-thumbnail__image" src="https://example.com/thumbnail.jpg" alt="Thumbnail for Test Presentation"><div class="qc-thumbnail__play-button qc-thumbnail__play-button--default"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="currentColor" width="64" height="64"><path d="M22.643 17.734a1 1 0 000-1.696L12.417 9.647a1 1 0 00-1.53.848v12.783a1 1 0 001.53.848l10.226-6.392zm-9.166 8.088a3 3 0 01-4.59-2.544V10.495a3 3 0 014.59-2.544l10.226 6.391a3 3 0 010 5.088l-10.226 6.392z"></path></svg></div></button></div>"`);
    });

    it('should render DialogComponent when playbackMode is modal', async () => {
      const modalConfiguration: WidgetConfiguration = {
        ...mockConfiguration,
        widgetOptions: {
          ...mockConfiguration.widgetOptions,
          playbackMode: 'modal',
        },
      };

      // eslint-disable-next-line no-new
      new PresentationWidget(modalConfiguration);

      await Promise.resolve();

      expect(container.querySelector('.qc-dialog')).not.toBeNull();
    });

    it('should render PlayerComponent when playbackMode is not modal', async () => {
      const nonModalConfiguration: WidgetConfiguration = {
        ...mockConfiguration,
        widgetOptions: {
          ...mockConfiguration.widgetOptions,
          playbackMode: 'inline',
        },
      };

      // eslint-disable-next-line no-new
      new PresentationWidget(nonModalConfiguration);

      await Promise.resolve();

      expect(container.querySelector('.qc-dialog')).toBeNull();
      expect(container.querySelector('.qc-thumbnail')).not.toBeNull();
    });

    it('should render PlayerComponent when playbackMode is undefined', async () => {
      const configWithoutPlaybackMode: WidgetConfiguration = {
        ...mockConfiguration,
        widgetOptions: {
          ...mockConfiguration.widgetOptions,
          playbackMode: undefined,
        },
      };

      // eslint-disable-next-line no-new
      new PresentationWidget(configWithoutPlaybackMode);

      await Promise.resolve();

      expect(container.querySelector('.qc-dialog')).toBeNull();
      expect(container.querySelector('.qc-thumbnail')).not.toBeNull();
    });
  });

  describe('destroy', () => {
    it('destroy the widget and clean up the DOM', async () => {
      const widget = new PresentationWidget(mockConfiguration);

      await Promise.resolve();

      expect(container.innerHTML).toMatchInlineSnapshot(`"<div class="qc-widget qc-presentation-widget"><button type="button" class="qc-thumbnail" style="place-items: center center;"><img class="qc-thumbnail__image" src="https://example.com/thumbnail.jpg" alt="Thumbnail for Test Presentation"><div class="qc-thumbnail__play-button qc-thumbnail__play-button--default"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="currentColor" width="64" height="64"><path d="M22.643 17.734a1 1 0 000-1.696L12.417 9.647a1 1 0 00-1.53.848v12.783a1 1 0 001.53.848l10.226-6.392zm-9.166 8.088a3 3 0 01-4.59-2.544V10.495a3 3 0 014.59-2.544l10.226 6.391a3 3 0 010 5.088l-10.226 6.392z"></path></svg></div></button></div>"`);

      widget.destroy();

      await Promise.resolve();

      expect(container.innerHTML).toMatchInlineSnapshot(`""`);
    });
  })
});
