import { afterEach, beforeEach, describe, expect, it, MockInstance, vi } from 'vitest';
import { PresentationWidget } from '@/widgets/presentation-widget';
import { WidgetConfiguration } from '@/interfaces/widget-configuration';
import { PresentationService } from '@/services/presentation.service';
import { Presentation } from '@/interfaces/presentation';

vi.mock('@/services/presentation.service');

describe('PresentationWidget', () => {
  const mockConfiguration: WidgetConfiguration = {
    guid: 'test-guid',
    host: 'example.com',
    selector: '.widget-container',
    widgetOptions: {
      playbackMode: 'inline',
    },
  };

  const mockPresentation: Presentation = {
    guid: 'test-guid',
    player: 'https://example.com/player',
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://example.com/thumbnail.jpg',
      height: 200,
      url: 'https://example.com/thumbnail.jpg',
      width: 300,
    },
    title: 'Test Presentation',
  };

  let container: HTMLElement;
  let getPresentationMock: MockInstance;

  beforeEach(() => {
    const div = document.createElement('div');

    div.classList.add('widget-container');
    document.body.appendChild(div);

    container = div;

    getPresentationMock = vi.spyOn(PresentationService.prototype, 'getPresentation')
      .mockResolvedValue(mockPresentation);
  });

  afterEach(() => {
    document.body.innerHTML = '';

    vi.restoreAllMocks();
    vi.clearAllMocks();
  });

  const flushPromises = () => new Promise(setImmediate);

  describe('constructor', () => {
    it('should initialize widget', async () => {
      const widget = await PresentationWidget.create(mockConfiguration);

      expect(widget).toBeDefined();
    });

    it('should validate the configuration and throw an error', async () => {
      const invalidConfig = {
        ...mockConfiguration,
        host: '   ',
      };

      await expect(() => PresentationWidget.create(invalidConfig)).rejects.toThrow('`host` cannot be an empty string');
    });
  });

  describe('init', () => {
    it('should fetch presentation and mount component', async () => {
      const querySelectorSpy = vi.spyOn(document, 'querySelector');

      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const widget = await PresentationWidget.create(mockConfiguration);

      await flushPromises();

      expect(getPresentationMock).toHaveBeenCalledWith(
        'test-guid',
        'example.com',
      );

      expect(querySelectorSpy).toHaveBeenCalledWith('.widget-container');
      expect(container.innerHTML)
        .toMatchInlineSnapshot(`"<div class="qc-widget qc-presentation-widget"><button type="button" style="place-items: center center;" class="qc-thumbnail"><img src="https://example.com/thumbnail.jpg" alt="Thumbnail for Test Presentation" class="qc-thumbnail__image"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="currentColor" width="44" height="44" aria-hidden="true" class="qc-icon qc-thumbnail__play-button qc-thumbnail__play-button--default"><path d="M22.643 17.734a1 1 0 000-1.696L12.417 9.647a1 1 0 00-1.53.848v12.783a1 1 0 001.53.848l10.226-6.392zm-9.166 8.088a3 3 0 01-4.59-2.544V10.495a3 3 0 014.59-2.544l10.226 6.391a3 3 0 010 5.088l-10.226 6.392z"></path></svg></button></div>"`);
    });

    it('throws error when container element is not found', async () => {
      vi.spyOn(document, 'querySelector').mockReturnValue(null);

      await expect(async () => await PresentationWidget.create(mockConfiguration)).rejects.toThrow('Element for selector ".widget-container" not found');
    });

    it('handles presentation service errors', async () => {
      const error = new Error('Network error');

      getPresentationMock.mockRejectedValue(error);

      await expect(async () => await PresentationWidget.create(mockConfiguration)).rejects.toThrow('Network error');
    });
  });

  describe('mount', () => {
    it('renders widget with presentation title and player component', async () => {
      await PresentationWidget.create(mockConfiguration);

      await flushPromises();

      expect(container.innerHTML)
        .toMatchInlineSnapshot(`"<div class="qc-widget qc-presentation-widget"><button type="button" style="place-items: center center;" class="qc-thumbnail"><img src="https://example.com/thumbnail.jpg" alt="Thumbnail for Test Presentation" class="qc-thumbnail__image"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="currentColor" width="44" height="44" aria-hidden="true" class="qc-icon qc-thumbnail__play-button qc-thumbnail__play-button--default"><path d="M22.643 17.734a1 1 0 000-1.696L12.417 9.647a1 1 0 00-1.53.848v12.783a1 1 0 001.53.848l10.226-6.392zm-9.166 8.088a3 3 0 01-4.59-2.544V10.495a3 3 0 014.59-2.544l10.226 6.391a3 3 0 010 5.088l-10.226 6.392z"></path></svg></button></div>"`);
    });

    it('uses HTMLElement from selector if provided', async () => {
      const querySelectorSpy = vi.spyOn(document, 'querySelector');
      const element = document.createElement('div');

      document.body.appendChild(element);

      const configWithHTMLElement: WidgetConfiguration = {
        ...mockConfiguration,
        selector: element,
      };

      await PresentationWidget.create(configWithHTMLElement);

      await flushPromises();

      expect(querySelectorSpy).not.toHaveBeenCalled();
      expect(element.innerHTML)
        .toMatchInlineSnapshot(`"<div class="qc-widget qc-presentation-widget"><button type="button" style="place-items: center center;" class="qc-thumbnail"><img src="https://example.com/thumbnail.jpg" alt="Thumbnail for Test Presentation" class="qc-thumbnail__image"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="currentColor" width="44" height="44" aria-hidden="true" class="qc-icon qc-thumbnail__play-button qc-thumbnail__play-button--default"><path d="M22.643 17.734a1 1 0 000-1.696L12.417 9.647a1 1 0 00-1.53.848v12.783a1 1 0 001.53.848l10.226-6.392zm-9.166 8.088a3 3 0 01-4.59-2.544V10.495a3 3 0 014.59-2.544l10.226 6.391a3 3 0 010 5.088l-10.226 6.392z"></path></svg></button></div>"`);
    });

    it('clears container innerHTML before mounting', async () => {
      const newDiv = document.createElement('div');

      newDiv.innerHTML = 'existing content';
      container.appendChild(newDiv);

      expect(container.innerHTML).toMatchInlineSnapshot(`"<div>existing content</div>"`);

      await PresentationWidget.create(mockConfiguration);

      // Wait for async init to complete
      await flushPromises();

      expect(container.innerHTML)
        .toMatchInlineSnapshot(`"<div class="qc-widget qc-presentation-widget"><button type="button" style="place-items: center center;" class="qc-thumbnail"><img src="https://example.com/thumbnail.jpg" alt="Thumbnail for Test Presentation" class="qc-thumbnail__image"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="currentColor" width="44" height="44" aria-hidden="true" class="qc-icon qc-thumbnail__play-button qc-thumbnail__play-button--default"><path d="M22.643 17.734a1 1 0 000-1.696L12.417 9.647a1 1 0 00-1.53.848v12.783a1 1 0 001.53.848l10.226-6.392zm-9.166 8.088a3 3 0 01-4.59-2.544V10.495a3 3 0 014.59-2.544l10.226 6.391a3 3 0 010 5.088l-10.226 6.392z"></path></svg></button></div>"`);
    });

    it('should render DialogComponent when playbackMode is modal', async () => {
      const modalConfiguration: WidgetConfiguration = {
        ...mockConfiguration,
        widgetOptions: {
          ...mockConfiguration.widgetOptions,
          playbackMode: 'modal',
        },
      };

      await PresentationWidget.create(modalConfiguration);

      await flushPromises();

      expect(container.querySelector('.qc-dialog')).not.toBeNull();
    });

    it('should render PlayerComponent when playbackMode is not modal', async () => {
      const nonModalConfiguration: WidgetConfiguration = {
        ...mockConfiguration,
        widgetOptions: {
          ...mockConfiguration.widgetOptions,
          playbackMode: 'inline',
        },
      };

      await PresentationWidget.create(nonModalConfiguration);

      await flushPromises();

      expect(container.querySelector('.qc-dialog')).toBeNull();
      expect(container.querySelector('.qc-thumbnail')).not.toBeNull();
    });

    it('should render PlayerComponent when playbackMode is undefined', async () => {
      const configWithoutPlaybackMode: WidgetConfiguration = {
        ...mockConfiguration,
        widgetOptions: {
          ...mockConfiguration.widgetOptions,
          playbackMode: undefined,
        },
      };

      await PresentationWidget.create(configWithoutPlaybackMode);

      await flushPromises();

      expect(container.querySelector('.qc-dialog')).toBeNull();
      expect(container.querySelector('.qc-thumbnail')).not.toBeNull();
    });
  });

  describe('destroy', () => {
    it('destroy the widget and clean up the DOM', async () => {
      const widget = await PresentationWidget.create(mockConfiguration);

      await flushPromises();

      expect(container.innerHTML)
        .toMatchInlineSnapshot(`"<div class="qc-widget qc-presentation-widget"><button type="button" style="place-items: center center;" class="qc-thumbnail"><img src="https://example.com/thumbnail.jpg" alt="Thumbnail for Test Presentation" class="qc-thumbnail__image"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="currentColor" width="44" height="44" aria-hidden="true" class="qc-icon qc-thumbnail__play-button qc-thumbnail__play-button--default"><path d="M22.643 17.734a1 1 0 000-1.696L12.417 9.647a1 1 0 00-1.53.848v12.783a1 1 0 001.53.848l10.226-6.392zm-9.166 8.088a3 3 0 01-4.59-2.544V10.495a3 3 0 014.59-2.544l10.226 6.391a3 3 0 010 5.088l-10.226 6.392z"></path></svg></button></div>"`);

      widget.destroy();

      await flushPromises();

      expect(container.innerHTML).toMatchInlineSnapshot(`""`);
    });
  });
});
