
export interface Presentation {
  audioOnly?: boolean;
  created?: string;
  duration?: number;
  guid?: string;
  metadata?: PresentationMetadata[];
  player?: string;
  public?: boolean;
  published?: Date;
  publisher?: PresentationUser;
  summary?: string;
  thumbnail?: PresentationThumbnail;
  title?: string;
  vod?: boolean;
}

export interface PresentationUser {
  guid: string;
  name: string;
  username: string;
}

export interface QcImage {
  cdnUrl?: string;
  height: number;
  url: string;
  width: number;
}

export interface PresentationThumbnail extends QcImage {
  autoGenerated: boolean;
}

export interface PresentationMetadata {
  guid: string;
  // The sanitized HTML when the value contains Markdown
  html?: string;
  title: string;
  type: MetadataType;
  value?: undefined;
}

export enum MetadataType {
  Boolean = 'BOOLEAN',
  Date = 'DATE',
  DatePast = 'DATE_PAST',
  DateTime = 'DATE_TIME',
  Email = 'EMAIL',
  LargeText = 'LARGE_TEXT',
  MultiSelect = 'MULTI_SELECT',
  Number = 'NUMBER',
  ProjectionType = 'PROJECTION_TYPE',
  Select = 'SELECT',
  Speech = 'SPEECH',
  State = 'STATE',
  StorageSize = 'STORAGE_SIZE',
  Tags = 'TAGS',
  Text = 'TEXT',
  TypeGuid = 'TYPE_GUID',
  UserGuid = 'USER_GUID',
  Views = 'VIEWS',
}
